version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    networks:
      - blog-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - blog-net

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: blog_db
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - blog-net

networks:
  blog-net:
